name: mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Formatação de entrada
  mask_text_input_formatter: ^2.0.1

  # Armazenamento local
  shared_preferences: ^2.0.0

  # Internacionalização
  intl: ^0.18.0

  # HTTP Requests
  http: ^1.2.2

  # WebSockets e Stomp
  stomp_dart_client: ^2.1.0
  sockjs_client_wrapper: ^1.3.0

  # Ícones padrão para iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Boas práticas de codificação
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets da aplicação
  assets:
    - assets/logo.png
